"""
ReportGenerator — creates a self-contained HTML cleaning report.
Shows before/after stats, per-column changes, and audit trail.
"""
from __future__ import annotations

from datetime import datetime
import json
import logging
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DataPure Cleaning Report</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         margin: 0; padding: 24px; background: #f8fafc; color: #1e293b; }}
  h1 {{ color: #0f172a; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }}
  h2 {{ color: #1e40af; margin-top: 32px; }}
  .grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px;
           margin: 20px 0; }}
  .card {{ background: white; border-radius: 10px; padding: 18px;
           box-shadow: 0 1px 3px rgba(0,0,0,.1); text-align: center; }}
  .card .num {{ font-size: 28px; font-weight: 700; color: #3b82f6; }}
  .card .lbl {{ font-size: 13px; color: #64748b; margin-top: 4px; }}
  table {{ width: 100%; border-collapse: collapse; background: white;
           border-radius: 10px; overflow: hidden;
           box-shadow: 0 1px 3px rgba(0,0,0,.1); margin-bottom: 24px; }}
  th {{ background: #1e40af; color: white; padding: 10px 14px;
        text-align: left; font-size: 13px; }}
  td {{ padding: 9px 14px; border-bottom: 1px solid #e2e8f0;
        font-size: 13px; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:nth-child(even) {{ background: #f8fafc; }}
  .badge-ok {{ background: #dcfce7; color: #166534;
               padding: 2px 8px; border-radius: 10px; font-size: 11px; }}
  .badge-warn {{ background: #fef9c3; color: #854d0e;
                 padding: 2px 8px; border-radius: 10px; font-size: 11px; }}
  .badge-crit {{ background: #fee2e2; color: #991b1b;
                 padding: 2px 8px; border-radius: 10px; font-size: 11px; }}
  .footer {{ text-align: center; color: #94a3b8; font-size: 12px;
             margin-top: 40px; }}
  pre {{ background: #1e293b; color: #e2e8f0; padding: 16px;
         border-radius: 8px; font-size: 12px; overflow-x: auto; }}
</style>
</head>
<body>
<h1>🧹 DataPure Cleaning Report</h1>
<p style="color:#64748b">Generated: {timestamp}</p>

<h2>Overview</h2>
<div class="grid">
  <div class="card"><div class="num">{rows_before}</div>
    <div class="lbl">Rows before</div></div>
  <div class="card"><div class="num">{rows_after}</div>
    <div class="lbl">Rows after</div></div>
  <div class="card"><div class="num">{nulls_fixed}</div>
    <div class="lbl">Nulls fixed</div></div>
  <div class="card"><div class="num">{n_steps}</div>
    <div class="lbl">Cleaners run</div></div>
</div>

<h2>Pipeline Steps</h2>
<table>
  <tr>
    <th>#</th><th>Cleaner</th><th>Rows removed</th>
    <th>Nulls fixed</th><th>Time (ms)</th>
  </tr>
  {step_rows}
</table>

<h2>Column Changes</h2>
<table>
  <tr>
    <th>Column</th><th>Type</th>
    <th>Nulls before</th><th>Nulls after</th><th>Status</th>
  </tr>
  {col_rows}
</table>

<h2>Audit Log (JSON)</h2>
<pre>{audit_json}</pre>

<div class="footer">Generated by DataPure v0.1.0</div>
</body>
</html>"""


class ReportGenerator:
    """
    Generates a self-contained HTML report from a pipeline run.

    Usage:
        report = ReportGenerator()
        report.generate(
            df_before=df_original,
            df_after=df_cleaned,
            audit_log=pipeline.get_audit_log(),
            output_path="report.html",
        )
    """

    def generate(
        self,
        df_before: pd.DataFrame,
        df_after: pd.DataFrame,
        audit_log: list[dict],
        output_path: str = "datapure_report.html",
    ) -> Path:
        """Generate HTML report and save to output_path. Returns Path."""

        # Build step rows
        step_rows = ""
        for step in audit_log:
            step_rows += (
                f"<tr>"
                f"<td>{step['step']}</td>"
                f"<td><strong>{step['cleaner']}</strong></td>"
                f"<td>{step['rows_removed']}</td>"
                f"<td>{step['nulls_fixed']}</td>"
                f"<td>{step['duration_ms']}</td>"
                f"</tr>\n"
            )

        # Build column comparison rows
        col_rows = ""
        for col in df_before.columns:
            if col not in df_after.columns:
                col_rows += (
                    f"<tr><td>{col}</td>"
                    f"<td>{df_before[col].dtype}</td>"
                    f"<td>{df_before[col].isnull().sum()}</td>"
                    f"<td>—</td>"
                    f"<td><span class='badge-crit'>dropped</span></td></tr>\n"
                )
                continue

            nulls_before = int(df_before[col].isnull().sum())
            nulls_after = int(df_after[col].isnull().sum())
            if nulls_after == 0 and nulls_before > 0:
                status = "<span class='badge-ok'>fixed</span>"
            elif nulls_after > 0:
                status = "<span class='badge-warn'>partial</span>"
            else:
                status = "<span class='badge-ok'>OK</span>"

            col_rows += (
                f"<tr>"
                f"<td>{col}</td>"
                f"<td>{df_before[col].dtype}</td>"
                f"<td>{nulls_before}</td>"
                f"<td>{nulls_after}</td>"
                f"<td>{status}</td>"
                f"</tr>\n"
            )

        total_nulls_fixed = sum(s["nulls_fixed"] for s in audit_log)

        html = _HTML_TEMPLATE.format(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            rows_before=len(df_before),
            rows_after=len(df_after),
            nulls_fixed=total_nulls_fixed,
            n_steps=len(audit_log),
            step_rows=step_rows,
            col_rows=col_rows,
            audit_json=json.dumps(audit_log, indent=2),
        )

        path = Path(output_path)
        path.write_text(html, encoding="utf-8")
        logger.info("Report saved to %s", path.resolve())
        return path
